### ISSUE TITLE
Migration for Craft 2 users?

### ISSUE THREAD

**Issue by bossanova808** [mmikkel/IncognitoField-Craft3#1]
Hi

Just wondering if you perhaps have any plans to write a migration for those of us using this extensively with Craft 2 already?

I'm finding that each time I do a C2 to C3 database migration (which I am needing to do fairly regularly as I am migrating a huge, complex site...) - that all of my incognito fields are reporting the component class is missing.  

I briefly tried to hack it by putting the correct new component class name in, but then it complains about some settings stuff....not surprised that my nasty hack didn't work.

A migration that does the appropriate DB changes here would be a huge help!

**Comment by mmikkel** [comment]
Hi @bossanova808, thanks for contributing.

Hm, I haven't actually done a single Craft 2 -> Craft 3 migration yet myself, so this is a bit surprising – in my naïveté, I thought Craft would handle it automatically for a plugin with a matching handle (at least something as simple as a PlainText field).

I'll look into it when I have the chance, thanks for making me aware!

**Comment by bossanova808** [comment]
Yeah with the new namespacing it's  changed (the handle thing) `craft\mmikkel\incogito-field\field\IncognitoFieldType` is (roughly) right in terms of migrating the handle.  But yep changing that triggered an issue with maxlenght in settings so I thought best to ask you first since you know it best!

Happy  to help test or dig in if you need any help.

**Comment by mmikkel** [comment]
Yeah, it's not really surprising that it doesn't work; more that I haven't really given migrations a single thought (we haven't even _tried_ selling existing/old clients on Craft 3 yet, although we do use Craft 3 on all new projects).

It should be relatively simple to add a post-install migration to do the necessary work, though – can't give you an ETA as I'm pretty swamped ATM, but will look at it ASAP.

Hopefully it's still possible to change the fieldtype (in the fields' settings) from the old Craft 2 fieldtype to the new Craft 3 fieldtype, after installing the latter?

**Comment by bossanova808** [comment]
Yes for sure - but you lose all the configured settings of course.  I have about 20 in play so would prefer not to repeat the config!  (And especially so if I need to do it multiple times with each new C2 -> C3 import/migration!!)

I've plenty of other things to work on for a bit, though, so no huge worries re: timing - thanks!!

**Comment by bossanova808** [comment]
So I went ahead and hacked my own upgrade path here using a console command - there's a gist that has the code if you want to grab any of it - it migrates the fieldtype and the settings changes too.

https://gist.github.com/bossanova808/b30a643f28b8125d7a32c46df9da6044

**Comment by mmikkel** [comment]
@bossanova808 That's awesome, thanks a lot! The least I can do at this point is to include that in an `Install` migration for Incognito Field – will get that sorted ASAP!

**Comment by bossanova808** [comment]
No probs - again no real hurry from me as this gets me out of jail for now.  It works for me but obviously look it over to make sure I got the settings stuff ok in particular!

**Comment by bossanova808** [comment]
Hey - so the lack of this has been causing some problems with Supertable migrations with the arrival of 3.1 - Would love to see you look over this and implement a more official Craft 2 -> 3.1 migration if possible.

In a nutshell, the migration should follow & basically extend Craft's own migration here:
https://github.com/craftcms/cms/blob/develop/src/migrations/m170223_224012_plain_text_settings.php

**Comment by bossanova808** [comment]
```
        // Look for any old Incognito fields and in this case we also need to update their settings
        $fields = (new Query())
            ->select(['id', 'settings'])
            ->from(['{{%fields}}'])
            ->where(['in', 'type', ['IncognitoField']])
            ->all();

        if ($fields)
        {
            // Update Update each field and its settings
            foreach ($fields as $field)
            {
                $oldSettings = $field['settings'] ? Json::decode($field['settings']) : null;
                $newSettings = $this->_migrateIncognitoSettings($oldSettings);

                $db->createCommand()->update('{{%fields}}', [
                    'type' => IncognitoField::class,
                    'settings' => Json::encode($newSettings)
                ], ['id' => $field['id']])->execute();
            }
        }

and

    private function _migrateIncognitoSettings($oldSettings){

        if(!$oldSettings) {
            return null;
        }

        $newField = new IncognitoField();

        // Example old settings:
        //{"placeholder":"","maxLength":"","multiline":"1","initialRows":"1","mode":"readonly"}

        $newSettings = $newField->getSettings();

        //var_dump($newSettings);

        $newSettings['mode'] = $oldSettings['mode'] ?? 0;
        $newSettings['placeholder'] = $oldSettings['placeholder'] ?? '';
        $newSettings['code'] = $oldSettings['code'] ?? '';        
        $newSettings['multiline'] = $oldSettings['multiline'] ?? 0;
        $newSettings['initialRows'] = $oldSettings['initialRows'] ?? 0;
        $newSettings['charLimit'] = $oldSettings['maxLength'] ?? 0;
        $newSettings['columnType'] = $oldSettings['columnType'] ?? Schema::TYPE_TEXT;

        return $newSettings;
    }
```
was the gist, seems to have disappeared...

**Comment by carlcs** [comment]
@bossanova808 Incognito 1.1.1 now includes a Craft 3 migration

**Comment by bossanova808** [comment]
Yay!  But... Does your migration take care of the fact some of the settings have changed name?  See above. Am on a quick trip to Japan so can't actually try it out...

**Comment by carlcs** [comment]
Yes @bossanova808, it includes everything Craft’s own Craft 3 migration for plain text field does, and Incognito’s settings didn’t change. https://github.com/mmikkel/IncognitoField-Craft3/blob/master/src/migrations/m190226_225231_craft3.php#L29

**Comment by bossanova808** [comment]
Great Carl. Thanks for this (and the rest). I was avoiding PRs as I felt someone with more complete knowledge should look at these things; it's great that you have!  Much appreciated!
