### ISSUE TITLE
[FR] Ability to search Incognito field

### ISSUE THREAD

**Issue by xavianaxw** [mmikkel/IncognitoField-Craft3#12]
Not sure if the plugin already supports it but I'm unable to perform CraftCMS search on the field using GraphQL

```gql
query getHomes($homeSearch:String, $communitySearch:String, $itemsPerPage:Int) {
  homes:entries(
    section: ["homes", "housesLand"]
    search:$homeSearch
  ) {
    title
    ... on housesLand_default_Entry {
      statusTag: homeStatusTag
      price: homeDisplayPrice
      bedrooms: homeBedrooms
      bathrooms:homeBathrooms
      carport: homeCarport
      images:homeGalleryImages {
        id
        title
        url
      }
    }
    ... on homes_default_Entry {
      statusTag: homeStatusTag
      price: homeFromPrice
      bedrooms: homeBedrooms
      bathrooms:homeBathrooms
      carport: homeCarport
      images:homeGalleryImages {
        id
        title
        url
      }
    }
  }
}
```

variables:

```
{
  "homeSearch": "homeBedrooms:2",
}
```

Craft version : `3.6.4`
Incognito plugin version: `1.2.0`

Edit: I've ensured that the fields that I want to search have been enabled to use as search keywords.

**Comment by xavianaxw** [comment]
```
query getHomes {
  homes:entries(
    section: ["homes", "housesLand"],
    homeBedrooms: 2
  ) {
    title
    ... on housesLand_default_Entry {
      statusTag: homeStatusTag
      price: homeDisplayPrice
      bedrooms: homeBedrooms
      bathrooms:homeBathrooms
      carport: homeCarport
      images:homeGalleryImages {
        id
        title
        url
      }
    }
    ... on homes_default_Entry {
      statusTag: homeStatusTag
      price: homeFromPrice
      bedrooms: homeBedrooms
      bathrooms:homeBathrooms
      carport: homeCarport
      images:homeGalleryImages {
        id
        title
        url
      }
    }
  }
}
```

Meanwhile this works.

**Comment by mmikkel** [comment]
I know next to nothing about GraphQL, but Incognito Field simply extends the native PlainText field so I'd assume that it'd have GraphQL support out of the box.

Have you confirmed that the field's values is in fact included in the `searchindex` DB table?

**Comment by xavianaxw** [comment]
> You’ll probably have better luck working directly with the [Date/Time field’s query param](https://docs.craftcms.com/v3/date-time-fields.html#querying-elements-with-date-time-fields) rather than going through [search](https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#search), which isn’t really intended for numerical/date values.

https://github.com/craftcms/cms/issues/5626

I found this on another issue tracked on craftcms's github. Looks like numbers are not intended to work with `search` so I'll just go with my second graphql query. 

Although it didn't seem like it was getting search indexed. How do I ensure that my field get search indexed?

**Comment by xavianaxw** [comment]
```
php craft resave/entries --update-search-index
```

This did the trick for me to make sure everything was search indexed. 

I'm guessing since Incognito Field is technically Plain Text thus a string, the comment I made before this does not apply. Everything is working now. 

Thanks mikel :)

**Comment by mmikkel** [comment]
@xavianaxw Thanks for the follow-up.

Yeah, technically Incognito is just a native PlainText field, with some extra styling in the CP – so it should be functionally identical to PlainText in every way.

I guess what happened in your case is that at some point the "Use this field’s values as search keywords" checkbox for the Incognito field wasn't checked – it's a common gotcha that enabling search indexes for an existing field, doesn't automatically include the field's values in the index for existing elements.

**Comment by xavianaxw** [comment]
Yeah. At least I got it working now. Thanks again @mmikkel
