### ISSUE TITLE
How to add default dynamic value in a readonly text field?

### ISSUE THREAD

**Issue by masiorama** [mmikkel/IncognitoField-Craft3#19]
Hi there, I miss the point of having the possibility to add a readonly text field but without a way to fill it with a default value.

I get the approach on handling the _mode override_ but that means that the user can fill the value on some scenarios, while I (as admin) want to be able to set a default value (dynamically with twig, for example) and never let the user edit that value.

Is it possible with Incognito? Any hints? 
Thanks!

**Comment by mmikkel** [comment]
The original use case for readonly Incognito fields was in cases where you need to save some data on your elements (for example, from an external API or similar via a custom Yii module or plugin) that should be visible, but not editable, in the admin interface.

Incognito fields are simple PlainText fields under the hood and there's no way to set a "default" value for them via the control panel (you could do it programmatically in a module or plugin, for example via an `Entry::EVENT_BEFORE_SAVE` event handler). But if you want a field that is only editable for admins, you can add this to the "Mode Override" setting:

```twig
{{ currentUser.admin ? 'plain' : 'readonly' }}
```

**Comment by masiorama** [comment]
@mmikkel thanks for your quick reply.
Indeed as you suggested I decided to leverage on your plugin for the readonly functionality and then prepared a little module which uses the event User::EVENT_BEFORE_SAVE.
Thanks!
