### ISSUE TITLE
Field render override does not work

### ISSUE THREAD

**Issue by Saboteur777** [mmikkel/IncognitoField-Craft3#7]
Trying to override field rendering mode on Craft 3.4: set it to plain if the entry is new, otherwise set it to disabled.

Trying to use this code: 
```
{{ element.isNew ? 'plain' : 'disabled' }}
```

but it does not work, the field render mode is always the same.

**Comment by carlcs** [comment]
Thanks for bringing this up. The `{{ not element.id ? 'plain' }}` example from the readme doesn’t work with Craft 3.2 and later, where creating an entry starts with a draft element that gets an ID right away.

Can you try if this code works for your use case (see #8):

```twig
{{ element.getIsUnsavedDraft() ? 'plain' }}
 ```

**Comment by Saboteur777** [comment]
Thanks for your quick response, it works flawlessly!
